[programs.localnet]
parakeet = "BCvJA6zrbWKCzYSPuStDdbvjBBBTDh8z45QGS9MCio11"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/laszlo-ratesic/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
